### ISSUE TITLE
Kollisioner 

### ISSUE THREAD

**Issue by cmeiner** [AdaHep/Tank-Hero#8]
Funktionaliteten för kollisioner på spelplanen. 

Zombie och projektil kolliderar - Zombie försvinner.
Tank och objekt kolliderar - Tanken förlorar ett liv.
Zombie och EndOfLine kolliderar - Ett människoliv förloras + effekten som hör till. 
Objekt och EndOfLine kolliderar - Remove objekt (Egentligen samma med zombie)

**Comment by FrontFelix** [comment]
Man kan skjuta, men behövs fixa om man kör på något
